### ISSUE TITLE
Página formulario: registro

### ISSUE THREAD

**Issue by corp-0** [corp-0/Exp2_CastilloRiquelmeSandoval_006D#7]
- [x] Utilizar diferentes elementos en los formularios de acuerdo con su funcionalidad (mínimo 5 elementos por formularios de ingreso o selección de datos).
- [x] Considerar que las nuevas páginas a implementar sean responsive.
- [x] Validar cada formulario web por el lado del cliente para evitar ingreso inconsistente al programa.

**Comment by kanroot** [comment]
Integre una validación mediante la presión del boton, te obliga a rellenar los campos vacios o rellenados de forma incorrecta
.

**Comment by corp-0** [comment]
hiciste el pull request de eso?

**Comment by kanroot** [comment]
Quedo el pull request dentro del branch "inputs" a la espera de aceptación.
